version: '2'
services:
  front:
    build: ./front 
    volumes:
      - ./front:/app
    ports:
      - 4200:4200
  front-dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
    ports:
      - 80:4200
  api:
    build: ./dashboard 
    ports:
      - 8080:8080 
