version: '2'
services:
  front:
    build: ./front 
    volumes:
      - ./front/dashboard:/app
    ports:
      - 4200:4200
  front-dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/dashboard:/app
    ports:
      - 4200:4200
